### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by damianoneill** [andaru/netconf#1]
Hi @andaru not really an issue, do you have any examples of using this library?

Thanks,
Damian.

**Comment by andaru** [comment]
Hi, Damian;

There isn't a lot in the repo at present.  Primarily we have NETCONF transport framings (encoder and decoder) in the `rfc6242` package.  These types implement standard `io` package interfaces, the decoder for chunked framing and end-of-message framing offering an `io.Reader` filter and encoder an `io.Writer`.

For NETCONF-over-SSH transport itself, you can use golang's `ssh` package to build a client or server. There's no code in the repo for this, yet (search for "golang ssh netconf" to find some posts about how to wire up such an `*ssh.Client` in the meantime, if you're interested).

For production servers, I'll be providing a gRPC stream transport to connect the OpenSSH server (via a subsystem program using the gRPC client) to the NETCONF agent daemon (offering the gRPC stream transport service), in addition to a server transport using the standard library's `ssh` package. 

There is an example test which shows a (very) rudimentary example of a canned NETCONF session to elaborate on usage of the RFC6242 decoder, including the end-of-message to chunked framing protocol upgrade for `:base:1.1` agreed sessions after capabilities exchange.  The example elaborates on the environment, giving hints on how you could attach it to other inputs.

You'll find that at: https://github.com/andaru/netconf/blob/master/rfc6242/example_protocol_upgrade_test.go

I'm presently working on related core libraries for NETCONF client or server implementations, including an in-memory datastore and edit/commit/rollback workflow to support the breadth of features available to NETCONF's base RPCs and optional capabilities.  That's due to be posted shortly, after which I'll return to these libraries to flesh out the client and server NETCONF session implementations.

My apologies if this is a little underwhelming at present!  It's obviously a large project, I'm attempting to get the individual components out so developers can consider them or use them in new ways.  Thanks for checking things out and posting the issue. Let me know if you have any further questions or comments.

**Comment by damianoneill** [comment]
Thanks Andrew, appreciate the fast response.  I'll watch the repo for new activity in the future. 

Regards,
Damian.
